create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  uid text not null unique,
  subject text not null,
  sender text not null,
  received_at timestamptz not null,
  html text not null default '',
  text text not null default '',
  status text not null default 'new',
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  ordinal integer not null,
  heading text not null,
  body text not null,
  unique(article_id, ordinal)
);

create table if not exists public.sentences (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  section_id bigint not null references public.sections(id) on delete cascade,
  ordinal integer not null,
  source_text text not null,
  translation text not null default '',
  natural_paraphrase text not null default '',
  key_point text not null default '',
  chunks jsonb not null default '[]'::jsonb,
  vocabulary jsonb not null default '[]'::jsonb,
  unique(article_id, section_id, ordinal)
);

create table if not exists public.vocab (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete set null,
  sentence_id bigint references public.sentences(id) on delete set null,
  term text not null,
  meaning text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists articles_received_at_idx on public.articles(received_at desc);
create index if not exists sections_article_id_idx on public.sections(article_id);
create index if not exists sentences_article_id_idx on public.sentences(article_id);
create index if not exists sentences_section_id_idx on public.sentences(section_id);
create index if not exists vocab_created_at_idx on public.vocab(created_at desc);

alter table public.articles enable row level security;
alter table public.sections enable row level security;
alter table public.sentences enable row level security;
alter table public.vocab enable row level security;

drop policy if exists "anon read articles" on public.articles;
drop policy if exists "anon read sections" on public.sections;
drop policy if exists "anon read sentences" on public.sentences;
drop policy if exists "anon read vocab" on public.vocab;
drop policy if exists "anon insert vocab" on public.vocab;

create policy "anon read articles" on public.articles for select to anon using (true);
create policy "anon read sections" on public.sections for select to anon using (true);
create policy "anon read sentences" on public.sentences for select to anon using (true);
create policy "anon read vocab" on public.vocab for select to anon using (true);
create policy "anon insert vocab" on public.vocab for insert to anon with check (true);
